char* getStr(char *s, int k);
int check_choice();
int input_number(int choice1);
int input_check();
int size_str(char *str);
int ent_kol(int n, char *str);
char** add_string(int kol, char* str, int n);
int* made_mas(char** s, int kol);
int find_nom(int* mas, int kol);
char* input_str(int n);
int* check_same(char** str1, char** str2, int kol1, int kol2, char c);
char** new_str(char** str1, int *mas, int kol1);
int find_kol(int *mas, int kol1);
void first();
void second();
